#!/bin/sh
#
# JMXEval execution script
#
# Syntax: check_jmxeval <config-xml-file>
#
# If JAVA_HOME environment variable is not set, uncomment the following
# line and set the value as the path to root of the Java directory 
#
# JAVA_HOME=/path/to/jdk-1.5.0
#
# Executes JMXEval
#
LIB_DIR=`dirname $0`
$JAVA_HOME/bin/java -jar $LIB_DIR/jmxeval-1.2.0.jar $@
