#!/bin/sh
#
# JMXEval execution script
#
# Syntax: check_jmxeval <config-xml-file> [<options>]
#
# If JAVA_HOME environment variable is not set, uncomment the following
# line and set the value as the path to root of the Java directory 
#
# JAVA_HOME=/path/to/jdk-1.7.0
#
# Execute JMXEval
#
BASE_DIR="`dirname $0`"
"$JAVA_HOME/bin/java" -classpath "$BASE_DIR/jmxeval/lib/*" com.adahas.tools.jmxeval.App $@
